#!/bin/bash

#Remove any existing file
rm /mnt/disk1/dvb/kernel-compile-module.sh

#Grab master file
wget https://raw.githubusercontent.com/CHBMB/Unraid-DVB/master/build_scripts/kernel-compile-module.sh -P /mnt/disk1/dvb/

#Change permissions
chmod +x /mnt/disk1/dvb/kernel-compile-module.sh

#Uncomment stable line
sed -i '64 s|#||' /mnt/disk1/dvb/kernel-compile-module.sh
