#!/bin/bash

#Remove any existing file
rm /mnt/disk1/dvb/ftp.sh

#Grab master file
wget https://raw.githubusercontent.com/CHBMB/Unraid-DVB/master/other_scripts/ftp.sh -P /mnt/disk1/dvb/

#Change permissions
chmod +x /mnt/disk1/dvb/ftp.sh

#Execute script
/mnt/disk1/dvb/ftp.sh